# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entpriseId', models.CharField(max_length=32, verbose_name='\u4f01\u4e1aid')),
                ('entName', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u540d\u79f0')),
                ('entReperson', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u6cd5\u4eba\u4ee3\u8868')),
                ('entAddress', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u5730\u5740')),
                ('entProduct', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u4ee3\u8868\u4e3b\u8981\u4ea7\u54c1')),
                ('entScale', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u751f\u4ea7\u89c4\u6a21')),
                ('entproductCycle', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u751f\u4ea7\u5468\u671f')),
                ('entCheckItem', models.CharField(max_length=200, verbose_name='\u4e3b\u8981\u68c0\u67e5\u9879\u76ee')),
                ('entType', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u6c61\u67d3\u7c7b\u578b')),
                ('entBusiness', models.CharField(max_length=200, verbose_name='\u6240\u5c5e\u884c\u4e1a')),
                ('entControl', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u88ab\u63a7\u5c5e\u6027')),
                ('createDate', models.DateField(blank=True, verbose_name='\u4f01\u4e1a\u521b\u5efa\u65f6\u95f4')),
                ('entPhone', models.DateField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('entPhoneName', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u4eba\u59d3\u540d')),
                ('entProductAndManage', models.CharField(max_length=10240, verbose_name='\u4f01\u4e1a\u751f\u4ea7\u548c\u7ba1\u7406\u670d\u52a1\u7684\u4e3b\u8981\u5185\u5bb9')),
                ('pollutionMethod', models.CharField(max_length=20, verbose_name='\u6392\u653e\u65b9\u5f0f\u8fde\u7eed\u6392\u653e')),
                ('entOtherInfo', models.CharField(max_length=20, verbose_name='\u4f01\u4e1a\u5176\u4ed6\u4fe1\u606f')),
                ('modifyDate', models.DateField(blank=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='EntProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entProduct', models.CharField(max_length=255, verbose_name='\u4e3b\u8981\u751f\u4ea7\u4ea7\u54c1')),
                ('entScale', models.CharField(max_length=255, verbose_name='\u4ea7\u54c1\u751f\u4ea7\u89c4\u6a21')),
                ('createDate', models.DateField(blank=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('entprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminInfo.Entprise', verbose_name='\u4f01\u4e1a')),
            ],
        ),
        migrations.CreateModel(
            name='EntUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entId', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u7ec4\u7ec7\u673a\u6784\u4ee3\u7801')),
                ('entName', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u540d\u79f0')),
                ('entOrganizationCode', models.CharField(max_length=255, verbose_name='\u767b\u9646\u4f01\u4e1a\u540d\u79f0')),
                ('userpassword', models.URLField(verbose_name='\u767b\u9646\u4f01\u4e1a\u5bc6\u7801')),
                ('loginTime', models.CharField(max_length=255, verbose_name='\u767b\u9646\u65f6\u95f4')),
                ('createDate', models.DateField(verbose_name='\u4f01\u4e1a\u521b\u5efa\u65e5\u671f')),
            ],
            options={
                'ordering': ['entName'],
            },
        ),
        migrations.CreateModel(
            name='EntZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entZoneName', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u5730\u533a')),
                ('entZoneCode', models.CharField(max_length=64, verbose_name='\u7b80\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='entprise',
            name='entUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminInfo.EntUser', verbose_name='\u4f01\u4e1a\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='entprise',
            name='entZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminInfo.EntZone', verbose_name='\u4f01\u4e1a\u8d26\u53f7'),
        ),
    ]
